# Generated by Django 5.1.4 on 2024-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTickets', '0003_ticket_precio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='precio',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
