# Generated by Django 5.1.4 on 2024-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoTickets', '0004_remove_ticket_precio_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_anónimo', max_length=150, unique=True),
        ),
    ]
